name: License

on:
  push:
  pull_request:

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
